# Generated by Django 4.0.5 on 2023-05-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='links_posts',
            new_name='category',
        ),
    ]
